apiVersion: v1
kind: Service
metadata:
  name: {{ include "howtoaks.fullnameFrontend" . }}
  labels:
    {{- include "howtoaks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "howtoaks.selectorLabelsFrontend" . | nindent 4 }}
